# Generated by Django 5.2.11 on 2026-02-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_content_project_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('PAINTING', 'Painting'), ('DRAWING', 'Drawing'), ('DIGITAL', 'Digital'), ('PHOTOGRAPHY', 'Photography'), ('MIXED_MEDIA', 'Mixed Media'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('image', models.ImageField(upload_to='artwork/')),
                ('medium', models.CharField(blank=True, help_text='e.g. Oil on Canvas', max_length=100)),
                ('dimensions', models.CharField(blank=True, help_text='e.g. 36" x 48"', max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(help_text='Short description for the gallery overlay')),
                ('content', models.TextField(blank=True, help_text='Full details/story for the detail view')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ArtPiece',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
