# Generated by Django 5.2.11 on 2026-02-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_artwork_delete_artpiece_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portrait',
            field=models.ImageField(blank=True, help_text='Photo for About Me section', null=True, upload_to='profile/'),
        ),
    ]
