# Generated by Django 6.0.1 on 2026-02-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_profile_portrait'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['order', '-year', '-created_at']},
        ),
        migrations.AddField(
            model_name='artwork',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in the gallery (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to video (YouTube/Vimeo) or animation'),
        ),
    ]
