# Generated by Django 6.0.1 on 2026-02-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='completion_date',
            field=models.DateField(blank=True, help_text='Date the artwork was completed', null=True),
        ),
    ]
