# Generated by Django 5.2.11 on 2026-02-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_artwork_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_title',
            field=models.CharField(default='About Me', help_text='Title for the About section', max_length=100),
        ),
    ]
