# Generated by Django 5.2.11 on 2026-02-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_profile_about_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Optional secondary image', null=True, upload_to='artwork/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Optional third image', null=True, upload_to='artwork/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Optional fourth image', null=True, upload_to='artwork/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(help_text='Main primary image', upload_to='artwork/'),
        ),
    ]
