# Generated by Django 5.2.11 on 2026-02-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_artwork_image_2_artwork_image_3_artwork_image_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4, WebM)', null=True, upload_to='videos/'),
        ),
    ]
