# Generated by Django 5.2.11 on 2026-02-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_artwork_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='program',
            field=models.CharField(blank=True, help_text='Software used, e.g. Photoshop, Blender', max_length=100),
        ),
    ]
